name: CI

on:
  pull_request:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  tests:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.10" ]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          python-version: "${{ matrix.python-version }}"
          venv-id: "tests-${{ runner.os }}"
      - run: echo "$CDSAPIRC" > ~/.cdsapirc
        env:
          CDSAPIRC: ${{ secrets.CDSAPIRC }}
        shell: bash
      - name: Run tests
        run: |
          pytest -r a -v tests -k 002
#      - name: Upload coverage reports to Codecov
#        uses: codecov/codecov-action@v3